/**
 * Controller: AuthorController
 * Generated by routerPlus
 */

const Author = require('../models/author');
const Book = require('../models/book');

class AuthorController {
  // GET / - Display a listing of the resource
  async index(req, res) {
    let searchOptions = {};
    if (req.query.name != null && req.query.name != '') {
      searchOptions.name = new RegExp(req.query.name, 'i');
    }

    await Author.find(searchOptions)
      .then((authors) =>
        res.render('authors/index', {
          authors: authors,
          searchOptions: req.query,
        }),
      )
      .catch((error) => res.redirect('/'));
  }

  // GET /new - Show form to create a new resource
  async create(req, res) {
    res.render('authors/new', { author: new Author() });
  }

  // POST / - Store a newly created resource in storage
  async store(req, res) {
    const author = new Author({
      name: req.body.name,
    });
    await author
      .save()
      .then((result) => res.redirect('/authors'))
      .catch((error) =>
        res.render('authors/new', {
          author: author,
          errorMessage: 'Error creating Author',
        }),
      );
  }

  // GET /:id - Display the specified resource
  async show(req, res) {
    try {
      const author = await Author.findById(req.params.id);
      const books = await Book.find({ author: author.id }).limit(6).exec();
      res.render('authors/detail', { author: author, booksByAuthor: books });
    } catch (error) {
      res.redirect('/authors');
    }
  }

  // GET /:id/edit - Show form for editing the resource
  async edit(req, res) {
    await Author.findById(req.params.id)
      .then((author) => res.render('authors/edit', { author: author }))
      .catch((error) => res.redirect('/authors'));
  }

  // PUT/PATCH /:id - Update the specified resource in storage
  async update(req, res) {
    let author;
    try {
      author = await Author.findById(req.params.id);
      author.name = req.body.name;
      await author.save();
      res.redirect(`/authors/${author.id}`);
    } catch (error) {
      if (author == null) {
        res.redirect('/authors');
      } else {
        res.render('authors/edit', {
          author: author,
          errorMessage: 'Error editing author',
        });
      }
    }
  }

  // DELETE /:id - Remove the specified resource from storage
  async destroy(req, res) {
    let author;
    try {
      author = await Author.findById(req.params.id);
      await author.deleteOne();
      res.redirect(`/authors`);
    } catch (error) {
      if (author == null) {
        res.redirect('/authors');
      } else {
        res.redirect(`/authors/${author.id}`);
      }
    }
  }
}

module.exports = new AuthorController();
