/**
 * Controller: AuthorController
 * Generated by routerPlus
 */

const Author = require('../models/author');

class AuthorController {
  // GET / - Display a listing of the resource
  async index(req, res) {
    let searchOptions = {};
    if (req.query.name != null && req.query.name != '') {
      searchOptions.name = new RegExp(req.query.name, 'i');
    }

    await Author.find(searchOptions)
      .then((authors) =>
        res.render('authors/index', {
          authors: authors,
          searchOptions: req.query,
        }),
      )
      .catch((error) => res.redirect('/'));
  }

  // GET /new - Show form to create a new resource
  async create(req, res) {
    res.render('authors/new', { author: new Author() });
  }

  // POST / - Store a newly created resource in storage
  async store(req, res) {
    const author = new Author({
      name: req.body.name,
    });
    await author
      .save()
      .then((result) => res.redirect('/authors'))
      .catch((error) =>
        res.render('authors/new', {
          author: author,
          errorMessage: 'Error creating Author',
        }),
      );
  }

  // GET /:id - Display the specified resource
  async show(req, res) {
    res.send('Show Author ' + req.params.id);
  }

  // GET /:id/edit - Show form for editing the resource
  async edit(req, res) {
    res.send('Edit Author ' + req.params.id);
  }

  // PUT/PATCH /:id - Update the specified resource in storage
  async update(req, res) {
    res.send('Update Author ' + req.params.id);
  }

  // DELETE /:id - Remove the specified resource from storage
  async destroy(req, res) {
    res.send('Delete Author ' + req.params.id);
  }
}

module.exports = new AuthorController();
