/**
 * Controller: BookController
 * Generated by routerPlus
 */
const Book = require('../models/book');
const Author = require('../models/author');
const Category = require('../models/category');

async function renderNewPage(res, book, hasError = false) {
  try {
    const authors = await Author.find({});
    const categories = await Category.find({});
    const params = {
      authors: authors,
      book: book,
      categories: categories,
    };
    if (hasError) params.errorMessage = 'Error creating book';
    res.render('books/new', params);
  } catch (error) {
    res.redirect('/books');
  }
}

async function saveCover(book, coverEncoded) {
  if (coverEncoded == null) return;

  const imageMimeTypes = ['image/jpeg', 'image/png', 'image/gif', 'image/jpg'];

  const cover = JSON.parse(coverEncoded);
  if (cover != null && imageMimeTypes.includes(cover.type)) {
    book.coverImage = new Buffer.from(cover.data, 'base64');
    book.coverImageType = cover.type;
  }
}

class BookController {
  // GET / - Display a listing of the resource
  async index(req, res) {
    let query = Book.find();
    if (req.query.title != null && req.query.title != '') {
      query = query.regex('title', new RegExp(req.query.title, 'i'));
    }

    if (req.query.publishedBefore != null && req.query.publishedBefore != '') {
      query = query.lte('publishDate', req.query.publishedBefore);
    }

    if (req.query.publishedAfter != null && req.query.publishedAfter != '') {
      query = query.gte('publishDate', req.query.publishedAfter);
    }

    await query
      .exec()
      .then((books) =>
        res.render('books/index', {
          books: books,
          searchOptions: req.query,
        }),
      )
      .catch((error) => res.redirect('/'));
  }

  // GET /new - Show form to create a new resource
  async create(req, res) {
    renderNewPage(res, new Book());
  }

  // POST / - Store a newly created resource in storage
  async store(req, res) {
    const book = new Book({
      title: req.body.title,
      author: req.body.author,
      publishDate: new Date(req.body.publishDate),
      pageCount: req.body.pageCount,
      description: req.body.description,
      category: req.body.category,
    });

    saveCover(book, req.body.cover);

    await book
      .save()
      .then((result) => res.redirect('/books'))
      .catch(async (error) => {
        renderNewPage(res, book, true);
      });
  }

  // GET /:id - Display the specified resource
  async show(req, res) {
    res.send('BookController Show ID: ' + req.params.id);
  }

  // GET /:id/edit - Show form for editing the resource
  async edit(req, res) {
    res.send('BookController Edit Form ID: ' + req.params.id);
  }

  // PUT/PATCH /:id - Update the specified resource in storage
  async update(req, res) {
    res.send('BookController Update ID: ' + req.params.id);
  }

  // DELETE /:id - Remove the specified resource from storage
  async destroy(req, res) {
    res.send('BookController Destroy ID: ' + req.params.id);
  }
}

module.exports = new BookController();
