/**
 * Controller: BookController
 * Generated by routerPlus
 */
const Book = require('../models/book');
const Author = require('../models/author');
const Category = require('../models/category');

async function renderNewPage(res, book, hasError = false) {
  renderFormPage(res, book, 'new', hasError);
}

async function renderEditPage(res, book, hasError = false) {
  renderFormPage(res, book, 'edit', hasError);
}

async function renderFormPage(res, book, form, hasError = false) {
  try {
    const authors = await Author.find({});
    const categories = await Category.find({});
    const params = {
      authors: authors,
      book: book,
      categories: categories,
    };

    if (hasError) {
      if (form == 'edit') {
        params.errorMessage = 'Error Updating book';
      }

      if (form == 'new') {
        params.errorMessage = 'Error Creating book';
      }
    }
    res.render(`books/${form}`, params);
  } catch (error) {
    res.redirect('/books');
  }
}

async function saveCover(book, coverEncoded) {
  if (coverEncoded == null) return;

  const imageMimeTypes = ['image/jpeg', 'image/png', 'image/gif', 'image/jpg'];

  const cover = JSON.parse(coverEncoded);
  if (cover != null && imageMimeTypes.includes(cover.type)) {
    book.coverImage = new Buffer.from(cover.data, 'base64');
    book.coverImageType = cover.type;
  }
}

class BookController {
  // GET / - Display a listing of the resource
  async index(req, res) {
    let query = Book.find();
    if (req.query.title != null && req.query.title != '') {
      query = query.regex('title', new RegExp(req.query.title, 'i'));
    }

    if (req.query.publishedBefore != null && req.query.publishedBefore != '') {
      query = query.lte('publishDate', req.query.publishedBefore);
    }

    if (req.query.publishedAfter != null && req.query.publishedAfter != '') {
      query = query.gte('publishDate', req.query.publishedAfter);
    }

    await query
      .exec()
      .then((books) =>
        res.render('books/index', {
          books: books,
          searchOptions: req.query,
        }),
      )
      .catch((error) => res.redirect('/'));
  }

  // GET /new - Show form to create a new resource
  async create(req, res) {
    renderNewPage(res, new Book());
  }

  // POST / - Store a newly created resource in storage
  async store(req, res) {
    const book = new Book({
      title: req.body.title,
      author: req.body.author,
      publishDate: new Date(req.body.publishDate),
      pageCount: req.body.pageCount,
      description: req.body.description,
      category: req.body.category,
    });

    saveCover(book, req.body.cover);

    await book
      .save()
      .then((result) => res.redirect('/books'))
      .catch(async (error) => {
        renderNewPage(res, book, true);
      });
  }

  // GET /:id - Display the specified resource
  async show(req, res) {
    try {
      const book = await Book.findById(req.params.id).populate('author').exec();
      res.render('books/detail', { book: book });
    } catch (error) {
      console.log(error);
      redirect('/books');
    }
  }

  // GET /:id/edit - Show form for editing the resource
  async edit(req, res) {
    try {
      const book = await Book.findById(req.params.id);
      renderEditPage(res, book);
    } catch (error) {
      res.redirect('/');
    }
  }

  // PUT/PATCH /:id - Update the specified resource in storage
  async update(req, res) {
    let book;
    try {
      book = await Book.findById(req.params.id);
      book.title = req.body.title;
      book.author = req.body.author;
      book.publishDate = new Date(req.body.publishDate);
      book.pageCount = req.body.pageCount;
      book.description = req.body.description;
      if (req.body.cover != null && req.body.cover != '') {
        saveCover(book, req.body.cover);
      }
      await book.save();
      res.redirect(`/books/${book.id}`);
    } catch (error) {
      if (book != null) {
        renderEditPage(res, book, true);
      } else {
        redirect('/');
      }
    }
  }

  // DELETE /:id - Remove the specified resource from storage
  async destroy(req, res) {
    let book;
    try {
      book = await Book.findById(req.params.id);
      await book.deleteOne();
      res.redirect('/books');
    } catch (error) {
      console.log(error);
      if (book != null) {
        res.render('books/detail', {
          book: book,
          errorMessage: 'Could not remove book',
        });
      } else {
        res.redirect('/');
      }
    }
  }
}

module.exports = new BookController();
