/**
 * Controller: CategoryController
 * Generated by routerPlus
 */
const Category = require('../models/category');

class CategoryController {
  // GET / - Display a listing of the resource
  async index(req, res) {
    let searchOptions = {};
    if (searchOptions != null && searchOptions != '') {
      searchOptions.name = new RegExp(req.query.name, 'i');
    }

    await Category.find(searchOptions)
      .then((categories) =>
        res.render('categories/index', {
          categories: categories,
          searchOptions: req.query,
        }),
      )
      .catch((error) => {
        console.log(error);
        res.redirect('/');
      });
  }

  // GET /new - Show form to create a new resource
  async create(req, res) {
    res.render('categories/new', { category: new Category() });
  }

  // POST / - Store a newly created resource in storage
  async store(req, res) {
    const category = new Category({
      name: req.body.name,
    });
    await category
      .save()
      .then((result) => res.redirect('/categories'))
      .catch((error) => {
        res.render('categories/new', {
          category: category,
          errorMessage: 'Error creating new category',
        });
      });
  }

  // GET /:id - Display the specified resource
  async show(req, res) {
    res.send('CategoryController Show ID: ' + req.params.id);
  }

  // GET /:id/edit - Show form for editing the resource
  async edit(req, res) {
    res.send('CategoryController Edit Form ID: ' + req.params.id);
  }

  // PUT/PATCH /:id - Update the specified resource in storage
  async update(req, res) {
    res.send('CategoryController Update ID: ' + req.params.id);
  }

  // DELETE /:id - Remove the specified resource from storage
  async destroy(req, res) {
    res.send('CategoryController Destroy ID: ' + req.params.id);
  }
}

module.exports = new CategoryController();
