/**
 * Controller: indexController
 * Generated by routerPlus
 */
const Book = require('../models/book');

class indexController {
  // GET / - Display a listing of the resource
  async index(req, res) {
    try {
      const books = await Book.find({}).sort({ createdAt: 'desc' }).limit(10);
      res.render('index', { books: books });
    } catch (error) {
      const books = [];
    }
  }

  // GET /new - Show form to create a new resource
  //   async create(req, res) {
  //     res.send('indexController Create Form');
  //   }

  // POST / - Store a newly created resource in storage
  //   async store(req, res) {
  //     res.send('indexController Store');
  //   }

  // GET /:id - Display the specified resource
  //   async show(req, res) {
  //     res.send('indexController Show ID: ' + req.params.id);
  //   }

  // GET /:id/edit - Show form for editing the resource
  //   async edit(req, res) {
  //     res.send('indexController Edit Form ID: ' + req.params.id);
  //   }

  // PUT/PATCH /:id - Update the specified resource in storage
  //   async update(req, res) {
  //     res.send('indexController Update ID: ' + req.params.id);
  //   }

  // DELETE /:id - Remove the specified resource from storage
  //   async destroy(req, res) {
  //     res.send('indexController Destroy ID: ' + req.params.id);
  //   }
}

module.exports = new indexController();
